ALTER TABLE users ADD COLUMN fight_wins INT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN fight_losses INT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN fight_streak INT NOT NULL DEFAULT 0
